name: Build

on:
  push:
    branches:
    - main
    tags:
    - '*'

    paths-ignore:
    - "docs/**"
    - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: BigWigsMods/packager@master
      with:
        args: -p 865814
      env:
        CF_API_KEY: ${{ secrets.plusmouse_curseforge }}
